type = input("vvedite vid zhivotnogo: ")
age = int(input("vvedite vozrast zhivotnogo: "))
nick = input("vvedite klichku zhivotnogo: ")
print(f'Eto {type} po klichke "{nick}". Vozrast: {age} goda.')

stage1 = input("vvedite 1 etap razvitiya cheloveka: ")
stage2 = input("vvedite 2 etap razvitiya cheloveka: ")
stage3 = input("vvedite 3 etap razvitiya cheloveka: ")
stage4 = input("vvedite 4 etap razvitiya cheloveka: ")
stage5 = input("vvedite 5 etap razvitiya cheloveka: ")
stage6 = input("vvedite 6 etap razvitiya cheloveka: ")
stage7 = input("vvedite 7 etap razvitiya cheloveka: ")
print (stage1, stage2, stage3, stage4, stage5, stage6, stage7, sep='=>')